services:
  strava-service:
    container_name: strava-service
    build:
      context: .
      dockerfile: ./strava-service/Dockerfile
      args:
        - GPG_PRIVATE_KEY=${GPG_PRIVATE_KEY}
    ports:
      - "669:666"
    env_file:
      - ./strava-service/.env.docker
    networks:
      - running-net
  runner:
    container_name: runner
    build:
      context: .
      dockerfile: ./runner/Dockerfile
      args:
        - GPG_PRIVATE_KEY=${GPG_PRIVATE_KEY}
    ports:
      - "666:666"
    env_file:
      - ./runner/.env.docker
    depends_on:
      - strava-service
      - database-service
    networks:
      - running-net 
  http_gateway:
    container_name: http_gateway
    build:
      context: .
      dockerfile: ./httpGateway/Dockerfile
      args:
        - GPG_PRIVATE_KEY=${GPG_PRIVATE_KEY}
    ports:
      - "81:80"
      - "444:443"
    depends_on:
      - runner
    networks:
      - running-net
  database-service:
    container_name: database-service
    build:
      context: .
      dockerfile: ./database-service/Dockerfile
      args:
        - GPG_PRIVATE_KEY=${GPG_PRIVATE_KEY}
    ports:
      - "667:666"
    networks:
      - running-net
      - db-net
  postgres:
    container_name: running_postgres
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
      args:
        - GPG_PRIVATE_KEY=${GPG_PRIVATE_KEY}
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./volumes-data/postgres/data:/var/lib/postgresql/data
    user: "1000:1000"
    networks:
      - db-net
  running_app:
    container_name: running_app
    build:  
      context: .
      dockerfile: ./running_app/Dockerfile
      args:
        - GPG_PRIVATE_KEY=${GPG_PRIVATE_KEY}
    ports:
      - "8001:5000"
    restart: unless-stopped
    networks:
      - running-net
      - proxy-net
networks:
  running-net:
  db-net:
  proxy-net:
#      external:
#        name: proxy-net
