services:
  strava-service:
    container_name: strava-service
    build:
      context: .
      dockerfile: ./strava-service/Dockerfile
    ports:
      - "666:666"
    env_file:
      - ./strava-service/.env.docker
  runner:
    container_name: runner
    build:
      context: .
      dockerfile: ./runner/Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./runner/.env.docker
    depends_on:
      - strava-service
  database-service:
    container_name: database-service
    build:
      context: .
      dockerfile: ./database-service/Dockerfile
    ports:
      - "667:666"
    env_file:
      - .env.docker.postgres
      - .env.docker.postgres.secret
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    user: "1000:1000"
    env_file:
      - .env.docker.postgres
      - .env.docker.postgres.secret
  populate-db:
    container_name: populate-db
    build:
      context: .
      dockerfile: ./populate-db/Dockerfile
    ports:
      - 678:666
    env_file:
      - ./populate-db/.env.docker
      - ./populate-db/.env.docker.secret