services:
  strava-service:
    container_name: strava-service
    image: janmeckelholt/running_strava-service:${COMMIT}
    ports:
      - "669:666"
    env_file:
      - ./strava-service/.env.docker
    networks:
      - running-net
  runner:
    container_name: runner
    image: janmeckelholt/running_runner:${COMMIT}
    ports:
      - "666:666"
    env_file:
      - ./runner/.env.docker
    depends_on:
      - strava-service
      - database-service
    networks:
      - running-net 
  http_gateway:
    container_name: http_gateway
    image: janmeckelholt/running_http_gateway:${COMMIT}
    ports:
      - "81:80"
      - "444:443"
    depends_on:
      - runner
    networks:
      - running-net
  database-service:
    container_name: database-service
    image: janmeckelholt/running_database-service:${COMMIT}
    ports:
      - "667:666"
    networks:
      - running-net
      - db-net
  postgres:
    container_name: postgres
    image: janmeckelholt/running_postgres:${COMMIT}
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./volumes-data/postgres/data:/var/lib/postgresql/data
    user: "1000:1000"
    networks:
      - db-net
  running_app:
    container_name: running_app
    image: janmeckelholt/running_running_app:${COMMIT}
    ports:
      - "8001:5000"
    restart: unless-stopped
    networks:
      - running-net
      - proxy-net
networks:
  running-net:
  db-net:
  proxy-net:
    external:
      name: proxy-net
