version: '2.4'
services:
  strava-service:
    container_name: strava-service
    build:
      context: .
      dockerfile: ./strava-service/Dockerfile
    ports:
      - "669:666"
    networks:
      - running-net
    volumes:
      - ./volumes-data/strava-service:/go/src/running/volumes-data
    env_file:
      - .env.gpg.secret
  runner:
    container_name: runner
    build:
      context: .
      dockerfile: ./runner/Dockerfile
    ports:
      - "666:666"
      - "8001:443"
    depends_on:
      - strava-service
      - database-service
    networks:
      - running-net
    volumes:
      - ./volumes-data/runner:/go/src/running/volumes-data
    env_file:
      - .env.gpg.secret
  populate_db:
    container_name: populate_db
    build:
      context: .
      dockerfile: ./populate_db/Dockerfile
    ports:
      - "670:666"
    depends_on:
      - strava-service
      - database-service
    networks:
      - running-net
    volumes:
      - ./volumes-data/populate_db:/go/src/running/volumes-data
    env_file:
      - .env.gpg.secret
  http_gateway:
    container_name: http_gateway
    build:
      context: .
      dockerfile: ./http_gateway/Dockerfile
    ports:
      - "333:333"
    depends_on:
      - runner
    networks:
      - running-net
    volumes:
      - ./volumes-data/common:/go/src/running/common
      - ./volumes-data/http_gateway:/go/src/running/volumes-data
    env_file:
      - .env.gpg.secret
  database-service:
    container_name: database-service
    build:
      context: .
      dockerfile: ./database-service/Dockerfile
    ports:
      - "667:666"
    networks:
      - running-net
      - db-net
    volumes:
      - ./volumes-data/common:/go/src/running/common
      - ./volumes-data/database-service:/go/src/running/volumes-data
    env_file:
      - .env.gpg.secret
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    restart: unless-stopped
    ports:
      - "5432:5432"
    user: "$USERID:$USERID"
    networks:
      - db-net
    volumes:
      - ./volumes-data/postgres/data:/var/lib/postgresql/data
      - ./volumes-data/common:/common
      - ./volumes-data/postgres/certs:/volumes-data/certs
    env_file:
      - .env.gpg.secret
      - .env.postgres.secret
networks:
  running-net:
  db-net:
