services:
  strava-service:
    container_name: strava-service
    build:
      context: .
      dockerfile: ./strava-service/Dockerfile
    ports:
      - "666:666"
    env_file:
      - ./strava-service/.env
  runner:
    container_name: runner
    build:
      context: .
      dockerfile: ./runner/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - strava-service