services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./config:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    networks:
      - proxy-net # add other containers onto this network to use dns name
    restart: unless-stopped

volumes:
  mosquitto-config:
  mosquitto-data:
  mosquitto-log:
networks:
  proxy-net:
    external: true
    name: proxy-net