name: Build
on: push

jobs:
  build:
    name: Build, test and publish app Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the docker-compose stack
        run:  docker-compose rm -f && docker-compose build
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY}}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
          PLATFORM: linux/arm64
        
      - name: Get init logs
        run: docker-compose logs

      - name: Publish image(s)
        run: |
          docker tag running_http_gateway ${{ secrets.DOCKER_USERNAME}}/running_http_gateway:${{ github.sha }}  && \
          docker tag running_runner ${{ secrets.DOCKER_USERNAME}}/running_runner:${{ github.sha }} && \
          docker tag running_strava-service ${{ secrets.DOCKER_USERNAME}}/running_strava-service:${{ github.sha }} && \
          docker tag running_database-service ${{ secrets.DOCKER_USERNAME}}/running_database-service:${{ github.sha }} && \
          docker tag running_running_app ${{ secrets.DOCKER_USERNAME}}/running_running_app:${{ github.sha }} && \
          docker tag running_postgres ${{ secrets.DOCKER_USERNAME}}/running_postgres:${{ github.sha }} && \
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
          docker push ${{ secrets.DOCKER_USERNAME}}/running_http_gateway:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME}}/running_runner:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME}}/running_strava-service:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME}}/running_database-service:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME}}/running_running_app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME}}/running_postgres:${{ github.sha }}
